<script lang="ts">
  import Grid from "gridjs-svelte";
  import "gridjs/dist/theme/mermaid.css";

  const columns = ["status", "instance", "notes"];
  const data = [
    ["⛔", "noagendasocial.com", '"free speech zone"², harassment'],
    ["⛔", "qoto.org", '"free speech zone"², harassment'],
    ["⛔", "itmslaves.com", '"free speech zone"², noagenda affiliated'],
    ["⛔", "ryona.agency", "Alt-right trolls"],
    ["⛔", "truthsocial.co.in", "Alt-right trolls"],
    ["⛔", "freeatlantis.com", "Conspiracy theory instance"],
    ["⛔", "kenfm.quadplay.tv", "Conspiracy videos"],
    ["⛔", "tube.kenfm.de", "Conspiracy videos"],
    ["⛔", "tube.querdenken-711.de", "Conspiracy videos"],
    ["⛔", "social.urspringer.de", "Conspiracy, CoVid19 denier"],
    [
      "⛔",
      "meta-tube.de",
      "Conspiracy, CoVid19 denier videos https://fediblock.org/blocklist/#meta-tube.de",
    ],
    ["⛔", "play.xmr.101010.pl", "Cryptomining"],
    ["⛔", "f.haeder.net", "Discrimination"],
    ["⛔", "glindr.org", "Discrimination"],
    ["⛔", "kiwifarms.cc", "Discrimination"],
    ["⛔", "midnightride.rs", "Discrimination"],
    ["⛔", "pleroma.kitsunemimi.club", "Discrimination"],
    ["⛔", "poa.st", "Discrimination"],
    ["⛔", "spinster.xyz", "Discrimination"],
    ["⛔", "wintermute.fr.to", "Discrimination"],
    ["⛔", "yggdrasil.social", "Discrimination"],
    ["⛔", "rdrama.cc", 'Discrimination, "free speech zone"²'],
    ["⛔", "comfyboy.club", "Discrimination, racism"],
    ["⛔", "bae.st", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "beefyboys.club", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "beefyboys.win", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "cawfee.club", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "chudbuds.lol", 'Discrimination, racism, "free speech zone"²'],
    [
      "⛔",
      "detroitriotcity.com",
      'Discrimination, racism, "free speech zone"²',
    ],
    ["⛔", "eveningzoo.club", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "frennet.link", 'Discrimination, racism, "free speech zone"²'],
    [
      "⛔",
      "freecumextremist.com",
      'Discrimination, racism, "free speech zone"²',
    ],
    [
      "⛔",
      "freespeechextremist.com",
      'Discrimination, racism, "free speech zone"²',
    ],
    ["⛔", "gab.com, gab.ai", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "glowers.club", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "iddqd.social", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "jaeger.website", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "nicecrew.digital", 'Discrimination, racism, "free speech zone"²'],
    [
      "⛔",
      "pleroma.narrativerry.xyz",
      'Discrimination, racism, "free speech zone"²',
    ],
    ["⛔", "poster.place", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "seal.cafe", 'Discrimination, racism, "free speech zone"²'],
    ["⛔", "sneed.social", 'Discrimination, racism, "free speech zone"²'],
    [
      "⛔",
      "social.ancreport.com",
      'Discrimination, racism, "free speech zone"²',
    ],
    ["⛔", "social.teci.world", 'Discrimination, racism, "free speech zone"²'],
    [
      "⛔",
      "pleroma.rareome.ga",
      "Doesn't [respect blocks or status privacy](https://pleroma.rareome.ga/notice/113524), [lolicons](https://pleroma.rareome.ga/notice/55113)",
    ],
    ["⛔", "pleroma.nobodyhasthe.biz", "Doxxing and discrimination"],
    ["⛔", "daishouri.moe", "Fascism, openly advertises with swastika"],
    ["⛔", "freefedifollowers.ga", "Follower spam"],
    ["⛔", "clube.social", "Harassment"],
    ["⛔", "clubcyberia.co", "Homophobia"],
    ["⛔", "mastodon.popps.org", "Homophobia"],
    ["⛔", "tastingtraffic.net", "Homophobia"],
    ["⛔", "mastodon.network", "Impersonation linking to porn"],
    ["⛔", "aethy.com", "Lolicon"],
    ["⛔", "baraag.net", "Lolicon"],
    ["⛔", "lolicon.rocks", "Lolicon"],
    ["⛔", "shota.house", "Lolicon"],
    ["⛔", "rapemeat.solutions", "Lolicon and also, like, the domain name"],
    ["⛔", "lolison.top", "Lolicon, paedophilia"],
    ["⛔", "cum.salon", "Misogynic, pedophilia"],
    ["⛔", "ohai.su", "Offline"],
    ["⛔", "sneak.berlin", "privacy violation"],
    [
      "⛔",
      "libre.tube",
      "Promotion of violence and murder, multiple other violations of our rules",
    ],
    ["⛔", "honkwerx.tech", "Racism"],
    ["⛔", "paypig.org", "Racism"],
    ["⛔", "pl.natehiggers.online", "Racism"],
    ["⛔", "pl.info.natehiggers.online", "Racism"],
    ["⛔", "ns.auction", "Racism etc"],
    ["⛔", "eientei.org", "Racism, antisemitism"],
    ["⛔", "pieville.net", "Racism, antisemitism"],
    ["⛔", "shortstackran.ch", 'Racism, homophobia, "free speech zone"²'],
    ["⛔", "socnet.supes.com", 'Right wing "free speech zone"²'],
    ["⛔", "wiki-tube.de", "Right wing conspiracy videos"],
    ["⛔", "mstdn.foxfam.club", "Right wing twitter mirror"],
    ["⛔", "skippers-bin.com", "Same admin as neckbeard.xyz, same behaviour"],
    ["⛔", "solagg.com", "Scammers"],
    ["⛔", "pl.tkammer.de", "Transphobia"],
    ["⛔", "varishangout.net", "Transphobia, aggressive trolling"],
  ];

  console.log(data);
</script>

<div class="not-prose">
  <Grid {data} {columns} search sort />
</div>
